### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by mileshatz** [ContionMig/Millin-Injector#1]
error C2440: '=': 'ULONGLONG' - '_LIST_ENTRY *'

Common.h(23,10): fatal error C1083: içerme dosyası açılamıyor: 'imgui.h': No such file or directory

**Comment by kay0w0** [comment]
https://github.com/ocornut/imgui Download this, put it in "Millin-Injector-master\Millin Injector"

Make sure you're compiling in x64.

Hope I helped, have a nice day ^_^
